#pragma once


#define LED_PORT 1 //port B
#define LED_PIN_RED 20
#define LED_PIN_RED_MASK PORT_PB20
#define LED_PIN_GREEN 19
#define LED_PIN_GREEN_MASK PORT_PB19
#define LED_PIN_BLUE 18
#define LED_PIN_BLUE_MASK PORT_PB18

#define DEBUG_SERIAL_PORT 1
#define DEBUG_SERIAL_PIN_TX 8
#define DEBUG_SERIAL_PIN_RX 9